# -*- coding: utf-8 -*-
"""CLASSWORK 2[E-M ALGORITHM](DCS 630).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEbXd_Pp-E1t7XE6SVzKsewiJuWm6Pkp
"""

import numpy as np
import pandas as pd
from math import sqrt, pi, exp
# Given data
X = np.array([50, 55, 60, 65, 70, 85, 90, 95])
# Initial mean guesses
mu1, mu2 = 55, 85
# Assign each point to nearest cluster
cluster1 = X[np.abs(X - mu1) < np.abs(X - mu2)]
cluster2 = X[np.abs(X - mu2) <= np.abs(X - mu1)]
# Compute variances
var1 = np.var(cluster1, ddof=0)
var2 = np.var(cluster2, ddof=0)
print("Cluster 1 (English) data:", cluster1)
print("Cluster 2 (Math) data:", cluster2)
print("Variance of Cluster 1 (σ1²):", var1)
print("Variance of Cluster 2 (σ2²):", var2)

#Expectation Step(E-Step)
# Given data and initial parameters
X = np.array([50, 55, 60, 65, 70, 85, 90, 95], dtype=float)
mu1, mu2 = 55.0, 85.0
var1, var2 = 31.25, 87.5  # variances computed from initial parameters
pi1, pi2 = 0.5, 0.5

def gaussian_pdf(x, mu, var):
    # Multivariate factor reduces to 1D Gaussian PDF
    coef = 1.0 / np.sqrt(2 * np.pi * var)
    exponent = -0.5 * ((x - mu)**2) / var
    return coef * np.exp(exponent)

# Compute likelihoods and responsibilities
likelihood1 = gaussian_pdf(X, mu1, var1)
likelihood2 = gaussian_pdf(X, mu2, var2)

num1 = pi1 * likelihood1
num2 = pi2 * likelihood2
denom = num1 + num2

resp1 = num1 / denom  # P(cluster1 | x_i)
resp2 = num2 / denom  # P(cluster2 | x_i)

df = pd.DataFrame({
    'Xi': X,
    'Likelihood_cluster1': likelihood1,
    'Likelihood_cluster2': likelihood2,
    'Numerator1 (pi1 * L1)': num1,
    'Numerator2 (pi2 * L2)': num2,
    'Resp_cluster1 (gamma_i1)': resp1,
    'Resp_cluster2 (gamma_i2)': resp2
})

display(df) #display to show the dataframe

#Maximimation Step(M-Step)
# Given data and previous parameters (same as used in E-step)
X = np.array([50, 55, 60, 65, 70, 85, 90, 95], dtype=float)
mu1_old, mu2_old = 55.0, 85.0
var1_old, var2_old = 31.25, 87.5
pi1_old, pi2_old = 0.5, 0.5

def gaussian_pdf(x, mu, var):
    coef = 1.0 / sqrt(2 * np.pi * var)
    exponent = -0.5 * ((x - mu)**2) / var
    return coef * np.exp(exponent)
likelihood1 = gaussian_pdf(X, mu1_old, var1_old)
likelihood2 = gaussian_pdf(X, mu2_old, var2_old)
num1 = pi1_old * likelihood1
num2 = pi2_old * likelihood2
denom = num1 + num2
resp1 = num1 / denom
resp2 = num2 / denom

# M-step updates
N1 = resp1.sum()
N2 = resp2.sum()
N = len(X)
mu1_new = (resp1 * X).sum() / N1
mu2_new = (resp2 * X).sum() / N2
var1_new = (resp1 * (X - mu1_new)**2).sum() / N1
var2_new = (resp2 * (X - mu2_new)**2).sum() / N2
pi1_new = N1 / N
pi2_new = N2 / N
results = {
    'N1': N1, 'N2': N2,
    'mu1_new': mu1_new, 'mu2_new': mu2_new,
    'var1_new': var1_new, 'var2_new': var2_new,
    'pi1_new': pi1_new, 'pi2_new': pi2_new}
df= pd.DataFrame([results])
df.round(3)

# Running 5 EM iterations (E-step and M-step) starting from the original initial guesses
# Given data and initial parameters
X = np.array([50, 55, 60, 65, 70, 85, 90, 95], dtype=float)
mu1, mu2 = 55.0, 85.0
var1, var2 = 31.25, 87.5
pi1, pi2 = 0.5, 0.5

def gaussian_pdf(x, mu, var):
    # Multivariate factor reduces to 1D Gaussian PDF
    coef = 1.0 / np.sqrt(2 * np.pi * var)
    exponent = -0.5 * ((x - mu)**2) / var
    return coef * np.exp(exponent)

def log_likelihood(X, mu1, mu2, var1, var2, pi1, pi2):
    L1 = pi1 * gaussian_pdf(X, mu1, var1)
    L2 = pi2 * gaussian_pdf(X, mu2, var2)
    total = L1 + L2
    # Add a small epsilon to avoid log(0) which results in -inf
    return np.sum(np.log(total + 1e-100))

records = []
iterations = 5
for it in range(1, iterations+1):
    # E-step: responsibilities
    L1 = pi1 * gaussian_pdf(X, mu1, var1)
    L2 = pi2 * gaussian_pdf(X, mu2, var2)
    denom = L1 + L2
    # Add a small epsilon to the denominator to avoid division by zero
    resp1 = L1 / (denom + 1e-100)
    resp2 = L2 / (denom + 1e-100)

    # M-step: update parameters
    N1 = resp1.sum()
    N2 = resp2.sum()
    # Add a small epsilon to N1 and N2 to avoid division by zero
    mu1_new = (resp1 * X).sum() / (N1 + 1e-100)
    mu2_new = (resp2 * X).sum() / (N2 + 1e-100)
    var1_new = (resp1 * (X - mu1_new)**2).sum() / (N1 + 1e-100)
    var2_new = (resp2 * (X - mu2_new)**2).sum() / (N2 + 1e-100)
    pi1_new = N1 / len(X)
    pi2_new = N2 / len(X)

    # Update parameters for the next iteration
    mu1, mu2 = mu1_new, mu2_new
    var1, var2 = var1_new, var2_new
    pi1, pi2 = pi1_new, pi2_new

    ll = log_likelihood(X, mu1, mu2, var1, var2, pi1, pi2)
    records.append({
        'iter': it,
        'N1': round(N1,6), 'N2': round(N2,6),
        'mu1': round(mu1,6), 'mu2': round(mu2,6),
        'var1': round(var1,6), 'var2': round(var2,6),
        'pi1': round(pi1,6), 'pi2': round(pi2,6),
        'log_likelihood': round(ll,6)})
df_iters = pd.DataFrame(records)
df_iters.round(6)

# Compute and print final mean, proportion, and standard deviation for each cluster
# Extract final parameters from the previous run
mu1_final, mu2_final = df_iters.iloc[-1]['mu1'], df_iters.iloc[-1]['mu2']
pi1_final, pi2_final = df_iters.iloc[-1]['pi1'], df_iters.iloc[-1]['pi2']
var1_final, var2_final = df_iters.iloc[-1]['var1'], df_iters.iloc[-1]['var2']

std1_final = np.sqrt(var1_final)
std2_final = np.sqrt(var2_final)

final_summary = pd.DataFrame({
    'Cluster': ['Cluster 1 (English)', 'Cluster 2 (Math)'],
    'Mean (μ)': [mu1_final, mu2_final],
    'Std Dev (σ)': [std1_final, std2_final],
    'Proportion (π)': [pi1_final, pi2_final]})
final_summary.round(6)